/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.au;

import org.apache.commons.cli.ParseException;
import org.junit.jupiter.api.Test;

import java.util.Scanner;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test
    void appHasAGreeting() throws ParseException {
            App classUnderTest = new App();
            Scanner myObj = new Scanner(System.in);

            String inp= myObj.nextLine();
        System.out.println("*****************"+inp);
            String arg[] = new String[0];
            assertNotNull(classUnderTest.getGreeting( inp,arg));
        }
}
